import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireRole } from "@/lib/session";
import { createNotification } from "@/lib/notifications";

export const dynamic = 'force-dynamic';
const schema=z.object({type:z.enum(["COMPANY","INSTITUTION"]),id:z.string().min(1),decision:z.enum(["VERIFIED","REJECTED"])});
export async function GET(){let u;try{u=await requireRole("ADMIN")}catch(e:any){return NextResponse.json({error:e.message},{status:e.status??401})};const [companies,institutions]=await Promise.all([prisma.companyProfile.findMany({where:{user:{isDemo:true}},include:{user:{select:{name:true,email:true}}},orderBy:{updatedAt:"desc"}}),prisma.institutionProfile.findMany({where:{user:{isDemo:true}},include:{user:{select:{name:true,email:true}}},orderBy:{updatedAt:"desc"}})]);return NextResponse.json({companies,institutions});}
export async function POST(req:NextRequest){let u;try{u=await requireRole("ADMIN")}catch(e:any){return NextResponse.json({error:e.message},{status:e.status??401})};const p=schema.safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({error:"Invalid input"},{status:400});const d=p.data;let targetUserId="";let label=d.type.toLowerCase();if(d.type==="COMPANY"){const x=await prisma.companyProfile.update({where:{id:d.id},data:{verificationStatus:d.decision},include:{user:{select:{id:true}}}});targetUserId=x.user.id}else{const x=await prisma.institutionProfile.update({where:{id:d.id},data:{verificationStatus:d.decision},include:{user:{select:{id:true}}}});targetUserId=x.user.id}await createNotification({userId:targetUserId,type:"VERIFICATION_STATUS",title:`${d.type} verification ${d.decision.toLowerCase()}`,message:`Your ${label} verification request was ${d.decision.toLowerCase()}.`,href:d.type==="COMPANY"?"/company/dashboard":"/institution/dashboard"});await prisma.auditLog.create({data:{userId:u.id,action:`${d.type}_${d.decision}`,resourceType:d.type,resourceId:d.id}});return NextResponse.json({ok:true});}
