import {NextRequest,NextResponse} from "next/server";
import {z} from "zod";
import {prisma} from "@/lib/prisma";
import {requireVerifiedRole} from "@/lib/session";
import {createNotification} from "@/lib/notifications";

export const dynamic = 'force-dynamic';
const schema=z.object({status:z.enum(["applied","under_review","shortlisted","interview","accepted","rejected","joined","completed"])});
const allowed:Record<string,string[]|undefined>={applied:["under_review","rejected"],under_review:["shortlisted","rejected"],shortlisted:["interview","rejected"],interview:["accepted","rejected"],accepted:["joined","rejected"],joined:["completed"],completed:[],rejected:[]};
export async function PATCH(req:NextRequest,{params}:{params:{id:string}}){let user;try{user=await requireVerifiedRole("COMPANY")}catch(e:any){return NextResponse.json({error:e.message},{status:e.status??401})};const app=await prisma.application.findUnique({where:{id:params.id},include:{student:{select:{userId:true}},opportunity:{include:{company:true}}}});if(!app)return NextResponse.json({error:"Not found"},{status:404});if(app.opportunity.company.userId!==user.id)return NextResponse.json({error:"Forbidden"},{status:403});const p=schema.safeParse(await req.json().catch(()=>null));if(!p.success)return NextResponse.json({error:"Invalid status"},{status:400});const next=p.data.status; if(next!==app.status&&!allowed[app.status]?.includes(next))return NextResponse.json({error:`Invalid status transition from ${app.status} to ${next}.`},{status:400});const updated=await prisma.application.update({where:{id:app.id},data:{status:next}});await createNotification({userId:app.student.userId,type:"APPLICATION_STATUS",title:"Application updated",message:`Your application for ${app.opportunity.title} is now ${next.replace("_"," ")}.`,href:`/student/applications`});await prisma.auditLog.create({data:{userId:user.id,action:"APPLICATION_STATUS_CHANGED",resourceType:"Application",resourceId:app.id,metadataJson:JSON.stringify({from:app.status,to:next})}});return NextResponse.json(updated)}
