"use client";

import Link from "next/link";
import { Box, Button, Card, CardActionArea, CardContent, Chip, Container, Divider, Grid, Paper, Stack, Typography } from "@mui/material";
import BiotechOutlinedIcon from "@mui/icons-material/BiotechOutlined";
import GroupsOutlinedIcon from "@mui/icons-material/GroupsOutlined";
import SchoolOutlinedIcon from "@mui/icons-material/SchoolOutlined";

const workspaces = [
  { title: "Research opportunities", body: "Discover AYUSH clinical, formulation and evidence projects aligned with your expertise.", href: "/academician/research", icon: <BiotechOutlinedIcon /> },
  { title: "Research collaboration", body: "Build partnerships with institutions and companies around credible research outcomes.", href: "/academician/collaboration", icon: <GroupsOutlinedIcon /> },
  { title: "Mentorship studio", body: "Review mentorship requests and help students turn capability gaps into evidence.", href: "/academician/mentorship", icon: <SchoolOutlinedIcon /> },
];
export default function AcademicianDashboard() { return <Container maxWidth="xl" sx={{ py: { xs: 3, md: 5 } }}><Paper sx={{ p: { xs: 3, md: 5 }, bgcolor: "#e8f0e8", borderRadius: 3, border: 1, borderColor: "divider" }}><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" spacing={3} alignItems={{ md: "flex-end" }}><div><Typography variant="overline" color="primary">Academician research workspace</Typography><Typography variant="h1" sx={{ mt: 1 }}>Turn expertise into shared progress.</Typography><Typography color="text.secondary" sx={{ mt: 2, maxWidth: 720 }}>A focused workspace for AYUSH research, institutional collaboration, mentorship and industry translation.</Typography></div><Stack direction="row" spacing={1}><Button component={Link} href="/academician/research" variant="contained">Explore research</Button><Button component={Link} href="/academician/profile" variant="outlined">View expertise</Button></Stack></Stack></Paper><Grid container spacing={2} sx={{ mt: 2 }}><Grid item xs={12} md={7}><Paper sx={{ p: { xs: 2, md: 3 } }}><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography variant="overline" color="primary">Active workstreams</Typography><Typography variant="h2" sx={{ mt: .5 }}>Your research network</Typography></Box><Chip label="3 active" color="success" /></Stack><Stack spacing={1.5} sx={{ mt: 3 }}>{workspaces.map((workspace) => <Card key={workspace.title} variant="outlined"><CardActionArea component={Link} href={workspace.href}><CardContent><Stack direction="row" spacing={2} alignItems="flex-start"><Paper variant="outlined" sx={{ p: 1.25, color: "primary.main", display: "grid", placeItems: "center" }}>{workspace.icon}</Paper><Box><Typography variant="h3">{workspace.title}</Typography><Typography color="text.secondary" sx={{ mt: .5 }}>{workspace.body}</Typography></Box></Stack></CardContent></CardActionArea></Card>)}</Stack></Paper></Grid><Grid item xs={12} md={5}><Paper sx={{ p: { xs: 2, md: 3 }, height: "100%" }}><Typography variant="overline" color="primary">Faculty signal</Typography><Typography variant="h2" sx={{ mt: .5 }}>Research identity</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>Keep your expertise and AYUSH research interests current so institutions and companies can find the right collaboration context.</Typography><Divider sx={{ my: 3 }} /><Stack spacing={2}><Signal label="AYUSH expertise" value="Clinical evidence · formulation quality" /><Signal label="Institution" value="VJ Institute of Technology" /><Signal label="Mentorship" value="2 active mentees" /></Stack><Button component={Link} href="/academician/profile" fullWidth variant="outlined" sx={{ mt: 4 }}>Update profile</Button></Paper></Grid></Grid></Container>; }
function Signal({ label, value }: { label: string; value: string }) { return <Box><Typography variant="overline" color="text.secondary">{label}</Typography><Typography variant="body1" fontWeight={700}>{value}</Typography></Box>; }
