"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {useSession} from "next-auth/react";
import SkillPicker,{PickedSkill} from "@/components/SkillPicker";
import MultiSelectPills from "@/components/MultiSelectPills";
import {SKILLS,CAREER_PATHS} from "@/lib/skills";
const degrees=["BAMS","BHMS","BUMS","BSMS","BNYS","B.Pharm","M.Pharm","M.Sc","B.Sc","PhD","Other"];
const specs=["Ayurveda","Dravyaguna & Rasashastra","Kayachikitsa","Shalya Tantra","Shalakya Tantra","Swasthavritta","Homoeopathy","Unani Medicine","Siddha Medicine","Yoga & Naturopathy","Pharmacy","Pharmacognosy","Phytochemistry","Biotechnology","Clinical Research","Healthcare Informatics","Other"];
export default function StudentProfilePage(){const {data:session,status}=useSession({required:true});const router=useRouter();const [loading,setLoading]=useState(true),[photo,setPhoto]=useState<string>(""),[photoBusy,setPhotoBusy]=useState(false),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState<string|null>(null);const [degreeType,setDegreeType]=useState("BAMS"),[specialization,setSpecialization]=useState(specs[0]),[year,setYear]=useState(1),[cgpa,setCgpa]=useState(""),[location,setLocation]=useState(""),[institutionId,setInstitutionId]=useState(""),[institutions,setInstitutions]=useState<any[]>([]),[bio,setBio]=useState(""),[githubUrl,setGithubUrl]=useState(""),[linkedinUrl,setLinkedinUrl]=useState(""),[portfolioUrl,setPortfolioUrl]=useState(""),[resumeUrl,setResumeUrl]=useState(""),[discoverability,setDiscoverability]=useState("MATCHED_ONLY"),[careerInterests,setCareerInterests]=useState<string[]>([]),[projectSkillIds,setProjectSkillIds]=useState<string[]>([]),[experienceSkillIds,setExperienceSkillIds]=useState<string[]>([]),[skills,setSkills]=useState<PickedSkill[]>([]);
useEffect(()=>{if(status!=="authenticated")return;Promise.all([fetch('/api/student/profile').then(r=>r.json()),fetch('/api/institutions').then(r=>r.json())]).then(([p,ins])=>{setInstitutions(ins||[]);if(p){setPhoto(p.profilePhotoUrl||"");setDegreeType(p.degreeType||"BAMS");setSpecialization(p.specialization||specs[0]);setYear(p.year||1);setCgpa(p.cgpa!=null?String(p.cgpa):"");setLocation(p.location||"");setInstitutionId(p.institutionId||"");setBio(p.bio||"");setGithubUrl(p.githubUrl||"");setLinkedinUrl(p.linkedinUrl||"");setPortfolioUrl(p.portfolioUrl||"");setResumeUrl(p.resumeUrl||"");setDiscoverability(p.discoverability||"MATCHED_ONLY");const j=(x:string)=>{try{const v=JSON.parse(x||"[]");return Array.isArray(v)?v:[]}catch{return[]}};setCareerInterests(j(p.careerInterests));setProjectSkillIds(j(p.projectSkillIds));setExperienceSkillIds(j(p.experienceSkillIds));setSkills((p.skills||[]).map((s:any)=>({skillId:s.skillId,proficiency:s.proficiency})));}setLoading(false)}).catch(()=>{setError('Could not load your profile.');setLoading(false)})},[status]);
async function uploadPhoto(file:File){setPhotoBusy(true);setError(null);const fd=new FormData();fd.append("photo",file);const r=await fetch("/api/student/profile/photo",{method:"POST",body:fd});const b=await r.json().catch(()=>({}));if(!r.ok)setError(b.error||"Could not upload photo.");else setPhoto(b.url);setPhotoBusy(false)}
async function photoAction(action:"remove"|"reset-demo"){setPhotoBusy(true);setError(null);const fd=new FormData();fd.append("action",action);const r=await fetch("/api/student/profile/photo",{method:"POST",body:fd});const b=await r.json().catch(()=>({}));if(!r.ok)setError(b.error||"Could not update photo.");else setPhoto(b.url||"");setPhotoBusy(false)}
async function save(e:React.FormEvent){e.preventDefault();setError(null);setSaving(true);const r=await fetch('/api/student/profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({degreeType,specialization,year,cgpa:cgpa?Number(cgpa):null,location:location||null,institutionId:institutionId||null,bio:bio||null,githubUrl:githubUrl||null,linkedinUrl:linkedinUrl||null,portfolioUrl:portfolioUrl||null,resumeUrl:resumeUrl||null,discoverability,careerInterests,projectSkillIds,experienceSkillIds,skills})});setSaving(false);if(!r.ok){const b=await r.json().catch(()=>({}));setError(b.error||'Could not save profile.');return}setSaved(true);setTimeout(()=>setSaved(false),2200)}
if(status==='loading'||loading)return <div className="page-wrap text-slate-400">Loading profile…</div>;
return <div className="page-wrap max-w-4xl"><div className="mb-8"><p className="eyebrow">EMPLOYABILITY PROFILE</p><h1 className="text-3xl font-bold mt-1">Your capability profile</h1><p className="text-slate-500 mt-2">Keep the evidence that helps the matching engine understand what you can actually do.</p></div><form onSubmit={save} className="space-y-6"><section className="card p-6 photo-profile-panel"><div className="flex flex-col sm:flex-row items-center sm:items-start gap-5"><div className="photo-frame">{photo?<img src={photo} alt="Profile" />:<span>{((session?.user?.name)||"AC").slice(0,2).toUpperCase()}</span>}</div><div className="flex-1 text-center sm:text-left"><p className="eyebrow">PROFILE IDENTITY</p><h2 className="section-title mt-1">Your profile photo</h2><p className="text-sm text-slate-500 mt-1">Use a professional photo or illustration. Maximum 2 MB.</p><label className="btn-primary mt-4 cursor-pointer inline-flex">{photoBusy?"Uploading…":"Change photo"}<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" disabled={photoBusy} onChange={e=>{const f=e.target.files?.[0];if(f)uploadPhoto(f)}}/></label></div></div></section>
<section className="card p-6"><h2 className="section-title">Academic foundation</h2><div className="grid sm:grid-cols-2 gap-4 mt-4"><div><label className="label">Degree program</label><select className="input" value={degreeType} onChange={e=>setDegreeType(e.target.value)}>{degrees.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label">Specialization</label><select className="input" value={specialization} onChange={e=>setSpecialization(e.target.value)}>{specs.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label">Current year</label><select className="input" value={year} onChange={e=>setYear(Number(e.target.value))}>{[1,2,3,4,5].map(x=><option key={x} value={x}>Year {x}</option>)}</select></div><div><label className="label">CGPA</label><input className="input" type="number" step="0.01" min="0" max="10" value={cgpa} onChange={e=>setCgpa(e.target.value)}/></div><div><label className="label">Location</label><input className="input" value={location} onChange={e=>setLocation(e.target.value)} placeholder="e.g. Bengaluru"/></div><div><label className="label">Institution</label><select className="input" value={institutionId} onChange={e=>setInstitutionId(e.target.value)}><option value="">Select a verified institution</option>{institutions.map(i=><option key={i.id} value={i.id}>{i.institutionName}</option>)}</select></div></div></section>
<section className="card p-6"><h2 className="section-title">Career direction</h2><p className="text-sm text-slate-500 mt-1">Used only to improve opportunity and learning recommendations.</p><div className="mt-4"><MultiSelectPills options={CAREER_PATHS} value={careerInterests} onChange={setCareerInterests}/></div></section>
<section className="card p-6"><h2 className="section-title">Skills</h2><p className="text-sm text-slate-500 mt-1">Self-declared skills are kept distinct from assessed and verified evidence.</p><div className="mt-4"><SkillPicker value={skills} onChange={setSkills}/></div></section>
<section className="card p-6"><h2 className="section-title">Evidence</h2><div className="mt-4 space-y-5"><div><p className="label">Used in projects</p><MultiSelectPills options={SKILLS.map(s=>({id:s.id,label:s.label}))} value={projectSkillIds} onChange={setProjectSkillIds}/></div><div><p className="label">Used in internships / work</p><MultiSelectPills options={SKILLS.map(s=>({id:s.id,label:s.label}))} value={experienceSkillIds} onChange={setExperienceSkillIds}/></div></div></section>
<section className="card p-6"><h2 className="section-title">Recruiter context</h2><p className="text-sm text-slate-500 mt-1">This is not a social profile. These details help a recruiter evaluate a relevant match.</p><div className="grid sm:grid-cols-2 gap-4 mt-4"><div className="sm:col-span-2"><label className="label">Short bio</label><textarea className="input" rows={3} maxLength={600} value={bio} onChange={e=>setBio(e.target.value)} placeholder="What kind of work are you looking to learn and contribute to?"/></div><div><label className="label">GitHub</label><input className="input" type="url" value={githubUrl} onChange={e=>setGithubUrl(e.target.value)} placeholder="https://github.com/..."/></div><div><label className="label">LinkedIn</label><input className="input" type="url" value={linkedinUrl} onChange={e=>setLinkedinUrl(e.target.value)} placeholder="https://linkedin.com/in/..."/></div><div><label className="label">Portfolio website</label><input className="input" type="url" value={portfolioUrl} onChange={e=>setPortfolioUrl(e.target.value)} placeholder="https://..."/></div><div><label className="label">Resume link</label><input className="input" type="url" value={resumeUrl} onChange={e=>setResumeUrl(e.target.value)} placeholder="Private storage link later"/></div></div><div className="mt-5"><label className="label">Profile visibility</label><select className="input max-w-md" value={discoverability} onChange={e=>setDiscoverability(e.target.value)}><option value="PRIVATE">Private</option><option value="MATCHED_ONLY">Visible to recruiters for relevant matches</option><option value="APPLIED_ONLY">Visible to recruiters after I apply</option><option value="PUBLIC">Public portfolio</option></select></div></section>
{error&&<div className="rounded-xl bg-red-50 border border-red-100 text-red-700 p-3 text-sm">{error}</div>}<div className="flex flex-wrap gap-3 items-center"><button disabled={saving} className="btn-primary">{saving?'Saving…':'Save profile'}</button>{saved&&<span className="text-sm text-emerald-600">Saved</span>}<button type="button" className="btn-secondary" onClick={()=>router.push('/student/dashboard')}>View opportunities →</button></div></form></div>}
